### ISSUE TITLE
请问是如何解包逆向出来的

### ISSUE THREAD

**Issue by enwaiax** [jzksnsjswkw/smzdm-app#1]
感谢开源方法，想要学习请教一下思路，多谢。

**Comment by jzksnsjswkw** [comment]
[https://blog.51cto.com/u_15127634/4364469](url)
直接用的自吐算法

**Comment by jzksnsjswkw** [comment]
https://blog.51cto.com/u_15127634/4364469
frida

**Comment by enwaiax** [comment]
不明觉厉，膜拜大佬
